
import { Aside } from "@/components/admin/aside/page";
import { Header } from "@/components/admin/Header/page";
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header>
        <Aside />
      </Header>
      {children}
    </>
  )
}
